In [2]:
import database
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa,aggregate_raters

table = database.view_table('evaluations_table')

In [3]:
all_scores = []

## Getting array of array of scores

In [4]:
for row in table:
    row_scores = []
    for score in row[-6:]:
        row_scores.append(score)
    all_scores.append(row_scores)
    all_scores.append(row_scores)

In [5]:
print(len(all_scores))
print(all_scores)

4
[[5, 2, 4, 5, 4, 0], [5, 2, 4, 5, 4, 0], [5, 1, 4, 5, 3, 3], [5, 1, 4, 5, 3, 3]]


## Getting average ratings

Question Number:
1. How easy was the recipe to follow? **(Clarity)**
2. How creative or inventive is the recipe generated from the user-inputted ingredients? **(Creativity/Novelty)**
3. How well does the generated recipe suit your provided ingredients? **(Suitability)**
4. How doable and edible does the recipe appear to be based on your inputted ingredients and the generated recipe? **(Doability and Edibility)**
5. How likely are you to try the recipe generated from your inputted ingredients? **(Likelihood to Try)**
6. How would you rate the overall quality of the recipe generated from your inputted ingredients? **(Overall Recipe Quality)**

In [8]:
question_num = 6
index = question_num - 1

values = np.array(all_scores)[:, index]

average = np.mean(values)

print('Question', question_num, 'average score:', average)

[0 0 3 3]
Question 6 average score: 1.5


## Getting Fleiss Kappa

In [195]:
ratings = np.array(all_scores)
print(ratings)

test = np.array([[5,4,3,2,1], [1,2,3,4,5], [5,4,3,2,1], [1,2,3,4,5], [5,0,5,5,0], [5,0,5,5,0], [5,0,5,5,0]])
print(test)

kappa = fleiss_kappa(ratings)
print("Fleiss' Kappa:", kappa)

[[5 2 4 5 4 0]
 [5 2 4 5 4 0]
 [5 1 4 5 3 3]
 [5 1 4 5 3 3]]
[[5 4 3 2 1]
 [1 2 3 4 5]
 [5 4 3 2 1]
 [1 2 3 4 5]
 [5 0 5 5 0]
 [5 0 5 5 0]
 [5 0 5 5 0]]


AssertionError: 